# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: countries.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("countries.proto", :syntax => :proto3) do
    add_message "countries.Empty" do
    end
    add_message "countries.Data" do
      optional :_id, :string, 1
      optional :name, :string, 2
      optional :prefix, :string, 3
      optional :phone_prefix, :string, 4
      optional :active, :bool, 5
      repeated :state, :message, 7, "countries.Data.States"
    end
    add_message "countries.Data.States" do
      optional :_id, :string, 1
      optional :country_id, :string, 2
      optional :name, :string, 3
      optional :prefix, :string, 4
      optional :phone_prefix, :string, 5
      optional :active, :bool, 6
      repeated :cities, :message, 7, "countries.Data.States.Cities"
    end
    add_message "countries.Data.States.Cities" do
      optional :_id, :string, 1
      optional :state_id, :string, 2
      optional :name, :string, 3
      optional :prefix, :string, 4
      optional :phone_prefix, :string, 5
      optional :active, :bool, 6
    end
    add_message "countries.DataResponse" do
      optional :data, :message, 1, "countries.Data"
    end
    add_message "countries.DataMultipleResponse" do
      repeated :data, :message, 1, "countries.Data"
    end
  end
end

module Countries
  Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("countries.Empty").msgclass
  Data = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("countries.Data").msgclass
  Data::States = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("countries.Data.States").msgclass
  Data::States::Cities = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("countries.Data.States.Cities").msgclass
  DataResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("countries.DataResponse").msgclass
  DataMultipleResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("countries.DataMultipleResponse").msgclass
end
